# Generated by Django 2.2.5 on 2019-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterviews',
            name='readinterview',
            field=models.BooleanField(default=False),
        ),
    ]
