# Generated by Django 2.2.6 on 2019-10-10 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInterviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('interview_author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор собеседования')),
                ('time_of_creation', models.DateTimeField(blank=True, null=True, verbose_name='Время создания')),
                ('period_of_execution', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('reminder', models.DateTimeField(blank=True, null=True, verbose_name='Напоминание')),
                ('position', models.CharField(max_length=50, verbose_name='Предполагаемая должность')),
                ('organization', models.CharField(max_length=50, verbose_name='Организация')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='Ответственное лицо')),
                ('contact_responsible_person_1str', models.CharField(max_length=50, verbose_name='Контакты ответственного лица (1-я строчка)')),
                ('contact_responsible_person_2str', models.CharField(blank=True, max_length=50, null=True, verbose_name='Контакты ответственного лица (2-я строчка)')),
                ('location', models.CharField(max_length=50, verbose_name='Место проведения')),
                ('additional_information', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Дополнительная информация')),
                ('add_file', models.FileField(upload_to='', verbose_name='Вложения')),
                ('status', models.BooleanField(default=False)),
                ('check_status', models.BooleanField(default=True)),
                ('done_interview', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
        ),
    ]
