# Generated by Django 2.2.5 on 2019-10-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='sum_all_vacancies',
        ),
    ]
