# Generated by Django 2.2.5 on 2019-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_resume_sum_all_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='vacancies_all',
            field=models.ManyToManyField(blank=True, related_name='all_for_resume', to='client.Vacancy'),
        ),
    ]
