# Generated by Django 2.2.5 on 2019-09-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_answer_chat_message_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='подзадача')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Имя задачи')),
                ('text', models.TextField(null=True, verbose_name='Текст задачи')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_end', models.DateField(verbose_name='Дата окончания задачи')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.Subtasks')),
            ],
        ),
    ]
