# Generated by Django 2.2.5 on 2019-09-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_subtasks_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='sub',
        ),
        migrations.AddField(
            model_name='subtasks',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.Tasks'),
        ),
    ]
