# Generated by Django 2.2.6 on 2019-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20191011_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterviews',
            name='add_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Вложения'),
        ),
    ]
