# Generated by Django 2.2.5 on 2019-10-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_settings_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='title',
            new_name='name_setting',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='about_new_offers_status',
            new_name='name_setting_status',
        ),
    ]
