# Generated by Django 2.2.6 on 2019-10-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20191011_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinterviews',
            old_name='client',
            new_name='user',
        ),
    ]
