# Generated by Django 2.2.6 on 2019-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20191003_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='notification',
            field=models.ManyToManyField(blank=True, related_name='notifications_for_resume', to='client.Vacancy'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tumbler_on_off',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
