# Generated by Django 2.2.6 on 2019-10-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20191011_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinterviews',
            old_name='user',
            new_name='client',
        ),
    ]
