# Generated by Django 2.2.6 on 2019-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20191004_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='tumbler_on_off',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
