# Generated by Django 2.2.6 on 2019-10-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20191011_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='client_cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
