# Generated by Django 2.2.6 on 2019-10-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20191004_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='tumbler_on_off',
            field=models.CharField(max_length=50),
        ),
    ]
