# Generated by Django 2.2.6 on 2019-10-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20191011_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinterviews',
            old_name='client',
            new_name='user',
        ),
    ]
